global:
  scrape_interval: 15s
 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
 
  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['jenkins:8080']
 
  - job_name: 'sonarqube'
    static_configs:
      - targets: ['super-lamp-q7xw475rq994f4gvx-9000.app.github.dev:443']
    scheme: https