apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-devops-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-devops-app
  template:
    metadata:
      labels:
        app: java-devops-app
    spec:
      containers:
        - name: java-app
          image: heena98.jfrog.io/docker-devops/java-devops-app:3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SERVER_PORT
              value: "8081"
      imagePullSecrets:
        - name: jfrog-registry-secret
      


