apiVersion: v1
kind: Service
metadata:
  name: java-devops-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: java-devops-app
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30036
