apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: download-plugin
        image: curlimages/curl:latest
        command: ["sh", "-c"]
        args:
          - curl -u $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY -fLo /plugins/sonar-prometheus-exporter.jar https://heenak.jfrog.io/artifactory/docker-devops/sonar-prometheus-exporter-1.0.0-SNAPSHOT.jar
        env:
        - name: ARTIFACTORY_USER
          valueFrom:
            secretKeyRef:
              name: jfrog-auth
              key: username
        - name: ARTIFACTORY_API_KEY
          valueFrom:
            secretKeyRef:
              name: jfrog-auth
              key: apikey
        volumeMounts:
        - name: plugins
          mountPath: /plugins

      containers:
      - name: sonarqube
        image: sonarqube:lts-community
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: plugins
          mountPath: /opt/sonarqube/extensions/plugins

      volumes:
      - name: plugins
        emptyDir: {}
